dependencies/vulkan_1.3.296.0/x86_64/bin/glslc engine/shaders/Standard.vert -o 	engine/shaders/Standard.vert.spv
dependencies/vulkan_1.3.296.0/x86_64/bin/glslc engine/shaders/Standard.frag -o 	engine/shaders/Standard.frag.spv
dependencies/vulkan_1.3.296.0/x86_64/bin/glslc engine/shaders/Standard.comp -o 	engine/shaders/Standard.comp.spv
dependencies/vulkan_1.3.296.0/x86_64/bin/glslc engine/shaders/Debug.vert -o 	 	engine/shaders/Debug.vert.spv
dependencies/vulkan_1.3.296.0/x86_64/bin/glslc engine/shaders/Debug.frag -o 	 	engine/shaders/Debug.frag.spv
dependencies/vulkan_1.3.296.0/x86_64/bin/glslc engine/shaders/Shadow.vert -o 	engine/shaders/Shadow.vert.spv
dependencies/vulkan_1.3.296.0/x86_64/bin/glslc engine/shaders/Cubemap.vert -o 	engine/shaders/Cubemap.vert.spv
dependencies/vulkan_1.3.296.0/x86_64/bin/glslc engine/shaders/Cubemap.frag -o 	engine/shaders/Cubemap.frag.spv
dependencies/vulkan_1.3.296.0/x86_64/bin/glslc engine/shaders/Grid.vert -o 	engine/shaders/Grid.vert.spv
dependencies/vulkan_1.3.296.0/x86_64/bin/glslc engine/shaders/Grid.frag -o 	engine/shaders/Grid.frag.spv
